version: 2

sources:
  - name: yellow_tripdata
    description: A clone of a Postgres application database.
    quoting:
          database: false
          schema: false
          identifier: false
    database: workspace
    schema: default
    tables:
      - name: yellow_tripdata_2024_01
      - name: taxi_zone_lookup

